trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '=2.6.2'

- task: Cache@2
  inputs:
    key: 'gems | "$(Agent.OS)" | Gemfile'
    restoreKeys: | 
      gems | "$(Agent.OS)"
      gems
    path: $(BUNDLE_PATH)
  displayName: Cache gems

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    bundle exec ruby ./update.rb
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Update dependencies'